### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by frederikmann** [theonemule/fahclient-azure-vm#3]
{"telemetryId":"542c53b5-d8ff-46d3-9839-dd639e9e9288","bladeInstanceId":"Blade_f26066f1b6444601b230dc061fcafda7_0_0","galleryItemId":"Microsoft.Template","createBlade":"DeployToAzure","code":"InvalidTemplateDeployment","message":"The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '9be752d1-86cd-4825-9231-8bdc00d66935'. See inner errors for details.","details":[{"code":"QuotaExceeded","message":"Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 4, Current Usage: 0, Additional Required: 6, (Minimum) New Limit Required: 6. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%2262fd7c5f-cc6e-4ed9-881d-ccd4d83cb1a7%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests."}]}

**Comment by theonemule** [comment]
You're out of cores. You can ask for more through an Azure support request.

https://docs.microsoft.com/en-us/azure/azure-portal/supportability/regional-quota-requests
